spring.application.name=miProyectoReserva
# postgresql details
spring.datasource.url=jdbc:postgresql://localhost:5432/dbreservas
spring.datasource.username=pwebuser
spring.datasource.password=pWEB123
spring.jpa.show-sql=true

spring.jpa.hibernate.ddl-auto=update

# docker run --name pwebpostgres -e POSTGRES_USER=pwebuser -e POSTGRES_PASSWORD=pWEB123 -p 5432:5432 -d postgres
#

app.jwt.secret = mysecretJ7Q16xGQkmEbE3fv4ecEmDkT5k3TkZZFg6srLt2YmpkEtjPfS28F3u
app.jwt.expirationMs = 43200000
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true